/* =====================================================================
   IT Engineer Learning Hub — glossary-data.js
   Searchable A–Z of the acronyms and terms an L1 engineer meets daily.
   Each: { term, full (expansion or ""), def, cat }
   ===================================================================== */
window.GLOSSARY = [
  { term: "AD", full: "Active Directory", cat: "Identity", def: "Microsoft's on-premises directory that stores users, computers and groups and handles sign-in for a traditional Windows network. The cloud successor is Entra ID." },
  { term: "ADUC", full: "Active Directory Users and Computers", cat: "Identity", def: "The classic on-prem tool for managing AD accounts — where you reset passwords, unlock accounts and edit group membership on a domain controller." },
  { term: "Entra ID", full: "Microsoft Entra ID (formerly Azure AD)", cat: "Identity", def: "Microsoft's cloud identity service. It authenticates users for Microsoft 365 and other cloud apps and is where you manage cloud accounts, MFA and Conditional Access." },
  { term: "SSO", full: "Single Sign-On", cat: "Identity", def: "Sign in once and get access to many apps without re-entering credentials for each." },
  { term: "MFA", full: "Multi-Factor Authentication", cat: "Identity", def: "Requires a second proof of identity (app approval, code, or key) on top of the password, so a stolen password alone isn't enough." },
  { term: "2FA", full: "Two-Factor Authentication", cat: "Identity", def: "The same idea as MFA but specifically two factors. In practice people use the terms interchangeably." },
  { term: "SSPR", full: "Self-Service Password Reset", cat: "Identity", def: "Lets users reset their own password after verifying identity, cutting the most common ticket you'll get. Registered at aka.ms/sspr." },
  { term: "TAP", full: "Temporary Access Pass", cat: "Identity", def: "A time-limited passcode in Entra ID used to bootstrap or recover an account — e.g. to register a new Authenticator when the old phone is gone." },
  { term: "Conditional Access", full: "", cat: "Identity", def: "Entra policies that decide whether a sign-in is allowed based on conditions (user, device, location, risk) — e.g. 'require MFA off the corporate network'." },
  { term: "Least privilege", full: "", cat: "Security", def: "Give an account only the access it needs to do its job — nothing more. Reduces damage if it's compromised." },
  { term: "RBAC", full: "Role-Based Access Control", cat: "Security", def: "Granting permissions via roles (e.g. Helpdesk Admin) rather than to individuals one by one." },
  { term: "GPO", full: "Group Policy Object", cat: "Devices", def: "A set of Windows/AD settings pushed to users or computers centrally — e.g. mapped drives, password rules, or printer deployment." },
  { term: "Intune", full: "Microsoft Intune", cat: "Devices", def: "Microsoft's cloud tool for managing and securing devices (MDM/MAM) — enrol laptops and phones, push apps and policy, and wipe lost devices." },
  { term: "MDM", full: "Mobile Device Management", cat: "Devices", def: "Managing enrolled devices centrally — configuration, apps, security policy and remote wipe. Intune is Microsoft's MDM." },
  { term: "RMM", full: "Remote Monitoring and Management", cat: "MSP", def: "The tool an MSP uses to watch client machines (alerts, patching) and fix them remotely. The engine room of managed IT." },
  { term: "PSA", full: "Professional Services Automation", cat: "MSP", def: "The ticketing, time-tracking and billing platform an MSP runs on. At Sempervox this is a Power Apps portal on Dataverse." },
  { term: "MSP", full: "Managed Service Provider", cat: "MSP", def: "A company that runs IT for other businesses on an ongoing, contracted basis — which is what Sempervox does." },
  { term: "SLA", full: "Service Level Agreement", cat: "MSP", def: "The agreed response and resolution times you're held to — e.g. 'P1 responded to within 30 minutes'. Missing SLAs has consequences." },
  { term: "Ticket", full: "", cat: "MSP", def: "The record of a customer request or issue in the PSA. Your day is worked through tickets — log everything in them." },
  { term: "Escalation", full: "", cat: "MSP", def: "Passing a ticket to a higher tier (L2/L3) or specialist when it's beyond your remit, access or knowledge. Escalate with a clean summary of what you've tried." },
  { term: "L1 / L2 / L3", full: "Support Tiers", cat: "MSP", def: "Levels of support. L1 = first line (the common, quick tickets — that's you). L2 = deeper technical. L3 = specialists/engineers." },
  { term: "Exchange Online", full: "", cat: "M365", def: "Microsoft's cloud email service in 365 — mailboxes, shared mailboxes, distribution lists and mail flow, managed in the Exchange admin center." },
  { term: "OWA", full: "Outlook on the Web", cat: "M365", def: "Webmail at outlook.office.com. Your first diagnostic test: if OWA works but the Outlook app doesn't, the problem is the client, not the mailbox." },
  { term: "NDR", full: "Non-Delivery Report", cat: "M365", def: "The bounce-back email you get when a message can't be delivered. Its code (e.g. 550, 5.7.1) tells you why." },
  { term: "Shared mailbox", full: "", cat: "M365", def: "A mailbox multiple people access (e.g. info@) that needs no licence under 50 GB. Permissions: Full Access, Send As, Send on Behalf." },
  { term: "Distribution list", full: "DL", cat: "M365", def: "An email group — send to one address and everyone in it receives it. Managed in the Exchange admin center." },
  { term: "Message trace", full: "", cat: "M365", def: "An Exchange admin tool that shows the path of an email — sent, delivered, blocked or quarantined — so you can prove what happened to a message." },
  { term: "Quarantine", full: "", cat: "M365", def: "Where suspected spam/phishing is held. You can review and release legitimate mail from the security portal." },
  { term: "SharePoint", full: "", cat: "M365", def: "Microsoft's cloud platform for team sites, document libraries and intranets. Permissions here (Owner/Member/Visitor) are a top source of access tickets." },
  { term: "OneDrive", full: "", cat: "M365", def: "Each user's personal cloud file storage in 365, syncing to their PC. Red X on the icon = a sync error." },
  { term: "Tenant", full: "", cat: "M365", def: "One organisation's isolated instance of Microsoft 365 (e.g. contoso.onmicrosoft.com). An MSP manages many tenants — one per client." },
  { term: "License pool", full: "", cat: "M365", def: "The stock of subscriptions a tenant owns. You assign a free one to a user; if none are free you must buy more (approval needed)." },
  { term: "Business Premium", full: "Microsoft 365 Business Premium", cat: "M365", def: "The common SMB licence bundling Office apps, Exchange, Teams, SharePoint plus security (Intune, Defender). Typical for MSP clients." },
  { term: "SIP", full: "Session Initiation Protocol", cat: "VoIP", def: "The signalling protocol that sets up, manages and ends VoIP calls — the 'dialling and ringing', not the audio itself." },
  { term: "RTP", full: "Real-time Transport Protocol", cat: "VoIP", def: "Carries the actual voice audio during a call. If SIP connects but you get one-way or no audio, RTP (often blocked by a firewall/NAT) is the suspect." },
  { term: "PBX", full: "Private Branch Exchange", cat: "VoIP", def: "The phone system that routes calls for an organisation. A hosted/cloud PBX lives in the provider's cloud rather than on-site." },
  { term: "DID", full: "Direct Inward Dialling", cat: "VoIP", def: "A phone number that rings a specific extension or user directly, without going through a receptionist." },
  { term: "SIP trunk", full: "", cat: "VoIP", def: "The virtual line connecting a PBX to the phone network over the internet, carrying multiple simultaneous calls." },
  { term: "IVR", full: "Interactive Voice Response", cat: "VoIP", def: "The 'press 1 for sales' auto-attendant menu that routes inbound callers." },
  { term: "Codec", full: "", cat: "VoIP", def: "How voice is compressed for transmission (e.g. G.711, G.729). Trades bandwidth against call quality." },
  { term: "Jitter", full: "", cat: "VoIP", def: "Variation in the arrival timing of voice packets. High jitter causes choppy, robotic audio." },
  { term: "Latency", full: "", cat: "VoIP", def: "Delay between speaking and being heard. Over ~150 ms it becomes noticeable and people start talking over each other." },
  { term: "QoS", full: "Quality of Service", cat: "VoIP", def: "Network settings that prioritise voice traffic over other data so calls stay clear when the connection is busy." },
  { term: "NAT", full: "Network Address Translation", cat: "Network", def: "How a router shares one public IP among many devices. A frequent cause of one-way audio in VoIP if not handled correctly." },
  { term: "DNS", full: "Domain Name System", cat: "Network", def: "Translates names (like outlook.office.com) into IP addresses. 'It's always DNS' is a running joke because it so often is." },
  { term: "DHCP", full: "Dynamic Host Configuration Protocol", cat: "Network", def: "Automatically hands out IP addresses to devices. A changed DHCP lease is why a network printer can suddenly go 'offline'." },
  { term: "VPN", full: "Virtual Private Network", cat: "Network", def: "An encrypted tunnel that lets a remote user securely reach internal resources as if on the office network." },
  { term: "Copilot", full: "Microsoft 365 Copilot", cat: "AI", def: "Microsoft's AI assistant built into the 365 apps — drafts, summarises and answers grounded in your own data, respecting existing permissions." },
  { term: "Power Automate", full: "", cat: "AI", def: "Microsoft's workflow automation tool — build 'when X happens, do Y' flows across apps. Cloud flows plus desktop RPA." },
  { term: "Copilot Studio", full: "", cat: "AI", def: "A low-code tool for building custom AI agents/chatbots (e.g. an internal helpdesk bot) on top of Dataverse and your knowledge sources." },
  { term: "Dataverse", full: "", cat: "AI", def: "The Microsoft cloud database behind Power Apps and Power Platform. Sempervox's ticket portal stores its data here." },
  { term: "RPA", full: "Robotic Process Automation", cat: "AI", def: "Automating repetitive clicks/keystrokes to mimic a person using an app — Power Automate Desktop is Microsoft's version." },
  { term: "LLM", full: "Large Language Model", cat: "AI", def: "The kind of AI (like the one behind Copilot) trained on huge text data to understand and generate language." }
];
